# Add the following 

title: Gabriel Palomarez
#logo: /assets/img/{head_shot_file.png}
#description: text below image
theme: jekyll-theme-minimal
#theme: jekyll-theme-time-machine
#theme: jekyll-theme-modernist
#theme: jekyll-theme-slate
