---
# Global Document Options
title: "Titanic Survival Analysis Portfolio"

# Execution Settings
execute:
  engine: jupyter
  python: "C:/Users/gabriel.palomarez/AppData/Local/anaconda3/python.exe"

# Output Format Settings
format:
  html:
    page-layout: full
    embed-resources: true
    grid:
      body-width: 1200px

# Chunk Options (Apply to all code blocks unless overridden)
echo: false
warning: false
---
